# Use Node.js LTS version
FROM node:20-slim

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install && \
    npm install --save-dev @types/express @types/node @types/socket.io @types/cors

# Copy app source
COPY . .

# Expose port
EXPOSE 4501

# Start the development server with hot reloading
CMD [ "npm", "run", "dev" ] 