version: '3.8'

services:
  movie-quotes:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4501:4501"
    environment:
      - NODE_ENV=development
    env_file:
      - /home/ariabel/coding/stream/notifications/.env
    networks:
      - traefik_net

networks:
  traefik_net:
    name: traefik_net
    external: true 