version: '3.8'

services:
  movie-quotes-bot:
    build: .
    container_name: movie-quotes-bot
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - stream-network
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  stream-network:
    name: stream-network
    external: true 